export const constants = {
  //goal
  GOAL_HEIGHT: 5,
  GOAL_WIDTH: 120,

  //field
  FIELD_LINES_THICKNESS: 5,
  PITCH_ROUNDED_RECT_RAD: 20,
  CENTER_CIRCLE_RAD: 55,

  // players
  FORWARD_CROSS_LENGTH: 30,
  DEFENDER_STROKE_WIDTH: 4,
  DEFENDER_CIRCLE_RAD: 15,
  PLAYER_PATH_STROKE_WIDTH: 2,
  FORWARD_TO_GOAL_LINE_STROKE_WIDTH: 3,
  DEFENSIVE_PLAYER_TARGET_POINT: 3,
};
